import type { PanelTextCode } from '@agentdeck/contracts/panel-agent';

/**
 * Русские запасные тексты действий над настройками, контуром, интеграциями,
 * переносом, аналитикой, копиями и каркасом плагина. Входят в `PANEL_TEXTS_RU`
 * одним спредом: пропуск кода краснеет там на сборке, подстановки сверяет
 * `texts.test.ts`, как у всех кодов.
 */
export const PANEL_MANAGE_TEXTS_RU = {
  'journal-read-split-defaults': 'Общие правила групп разделения',
  'journal-save-split-defaults': 'Правка общих правил групп разделения',
  'summary-save-split-defaults': 'Изменить общие правила групп разделения',
  'label-split-human-only': 'Остаётся за вами',
  'value-split-human-only': 'Права групп и развилки групп агент не меняет — их выставляете вы',
  'journal-read-sieves': 'Сита перед MR: выученные и счёт блокеров',
  'journal-delete-learned-sieve': 'Убрать выученное сито',
  'summary-delete-learned-sieve':
    'Убрать выученное сито класса «{{class}}» — оно перестанет попадать в задания групп',
  'label-sieve-sources': 'Выучено по тредам',
  'journal-watcher-status': 'Состояние фонового наблюдателя',
  'journal-set-watcher': 'Включение или выключение наблюдателя',
  'summary-watcher-on': 'Включить фоновый наблюдатель',
  'summary-watcher-off': 'Выключить фоновый наблюдатель',
  'label-watcher-cost': 'Расход',
  'value-watcher-cost': 'Сбои страниц разбирает модель в фоне — это тратит лимит',
  'value-watcher-off': 'Разбор останавливается сразу',
  'journal-list-models': 'Каталог моделей',
  'journal-format-check': 'Сверка форматов CLI',
  'journal-read-account': 'Учётная запись и система',
  'journal-cli-version': 'Версия CLI Claude',
  'journal-update-cli': 'Обновление CLI Claude',
  'summary-update-cli': 'Обновить CLI Claude',
  'label-cli-path': 'Копия CLI',
  'value-update-cli-effect':
    'Запускается «claude update» для этой копии, до 5 минут; новые запуски пойдут обновлённой',
  'value-version-unknown': 'не ответила на --version',
  'journal-dlp-preview': 'Проверка текста правилами защиты данных',
  'journal-dlp-journal': 'Журнал прокси защиты данных',
  'journal-clear-dlp-journal': 'Очистка журнала прокси защиты данных',
  'summary-clear-dlp-journal': 'Очистить журнал прокси защиты данных',
  'label-entries': 'Записей',
  'value-clear-dlp-journal': 'Записи журнала удаляются насовсем; правила и прокси не меняются',
  'journal-disable-contour': 'Снятие применения контура',
  'summary-disable-contour': 'Снять применение контура «{{title}}»',
  'label-applied-targets': 'Применён к',
  'value-applied-none': 'никуда не применён',
  'value-disable-contour-effect':
    'Файлы CLI вернутся в исходный вид; файл, который вы правили после, останется как есть. Сам контур не удаляется',
  'journal-deactivate-contour': 'Выключение контура',
  'summary-deactivate-contour': 'Выключить контур «{{title}}» и вернуть провайдера по умолчанию',
  'value-deactivate-contour-effect':
    'Запросы CLI снова идут провайдеру по умолчанию; применения контура снимаются',
  'journal-delete-contour': 'Удаление контура',
  'summary-delete-contour': 'Удалить контур «{{title}}»',
  'value-delete-contour-effect':
    'Уходят настройка, ключ и след проб; применение снимается до удаления',
  'journal-gateway-status': 'Состояние шлюза контура',
  'journal-start-gateway': 'Запуск шлюза контура',
  'summary-start-gateway': 'Поднять шлюз контура',
  'label-port': 'Порт',
  'value-start-gateway-effect': 'Шлюз включается в настройках и поднимается на этом порту',
  'journal-restart-gateway': 'Перезапуск шлюза контура',
  'summary-restart-gateway': 'Перезапустить шлюз контура',
  'value-restart-gateway-effect': 'Запросы, идущие через шлюз прямо сейчас, оборвутся',
  'journal-contour-spend': 'Расход контура',
  'journal-clear-contour-exhausted': 'Снятие отметки «бюджет исчерпан»',
  'summary-clear-contour-exhausted': 'Снять отметку «бюджет исчерпан» у контура «{{title}}»',
  'label-exhausted-at': 'Отказ по бюджету',
  'value-clear-exhausted-effect':
    'Снимайте, только если бюджет продлили: иначе контур снова ответит отказом',
  'journal-contour-mcp': 'MCP-сервер контура в CLI',
  'summary-contour-mcp-connect': 'Подключить инструменты контура к CLI как MCP-сервер',
  'summary-contour-mcp-disconnect': 'Отключить MCP-сервер контура от CLI',
  'label-mcp-server': 'MCP-сервер',
  'value-mcp-bridge-no-key': 'В записи нет ключа — только адрес панели',
  'value-mcp-disconnect-effect': 'Запись сервера уходит из конфигурации CLI',
  'journal-jira-projects': 'Проекты Jira',
  'journal-jira-search': 'Поиск задач Jira',
  'journal-jira-issue': 'Задача Jira',
  'journal-confluence-spaces': 'Пространства Confluence',
  'journal-confluence-search': 'Поиск страниц Confluence',
  'journal-confluence-page': 'Страница Confluence',
  'journal-list-integration-links': 'Привязки проекта',
  'journal-save-integration-link': 'Привязка проекта к задаче и странице',
  'summary-save-integration-link': 'Привязать проект «{{project}}»',
  'label-link-scope': 'Для',
  'value-link-project': 'всего проекта',
  'label-jira-issue': 'Задача Jira',
  'label-confluence-page': 'Страница Confluence',
  'label-forge-repo': 'Репозиторий',
  'label-note': 'Заметка',
  'journal-remove-integration-link': 'Снятие привязки проекта',
  'summary-remove-integration-link': 'Снять привязку проекта «{{project}}»',
  'journal-atlassian-mcp': 'MCP-сервер Atlassian в CLI',
  'summary-atlassian-mcp-disconnect': 'Отключить MCP-сервер Atlassian от CLI',
  'journal-portability-plan': 'План переноса среды',
  'journal-apply-portability': 'Перенос среды в другой CLI',
  'summary-apply-portability': 'Перенести среду {{source}} → {{target}}',
  'label-target-root': 'Куда',
  'value-portability-backup': 'Перед записью панель делает копии; перенос можно отменить',
  'journal-revert-portability': 'Отмена переноса среды',
  'summary-revert-portability': 'Отменить перенос {{source}} → {{target}}',
  'label-changed-since': 'Правились после переноса — останутся как есть',
  'value-changed-since-none': 'таких файлов нет',
  'journal-portability-transfer': 'След последнего переноса',
  'journal-portability-subscriptions': 'Подписки на среду',
  'journal-env-transfer-preview': 'Что попадёт в архив среды',
  'journal-env-transfer-export': 'Выгрузка архива среды',
  'summary-env-transfer-export': 'Собрать архив среды Claude Code',
  'label-archive-content': 'Содержимое',
  'value-archive-no-secrets':
    'Секретов в архиве нет: значения заменены меткой, на новой машине их вводят заново',
  'journal-analytics-live': 'Идущие агенты',
  'journal-session-where': 'Где идёт сессия',
  'journal-stop-session': 'Остановка сессии CLI',
  'summary-stop-session': 'Остановить сессию {{session}}',
  'label-process': 'Процесс',
  'journal-delete-backup': 'Удаление копии',
  'summary-delete-backup': 'Удалить копию «{{name}}»',
  'value-delete-backup-effect': 'Копия удаляется насовсем: из неё больше нельзя будет восстановить',
  'journal-scaffold-plugin': 'Каркас плагина',
  'summary-scaffold-plugin': 'Создать каркас плагина «{{name}}»',
  'label-components': 'Части',
  'value-components-none': 'только манифест и README',
} satisfies Partial<Record<PanelTextCode, string>>;
