import {
  formatPanelText,
  type PanelActionPreviewField,
  type PanelPluralForm,
  type PanelTextCode,
  type PanelTextCountCode,
  type PanelTextParams,
} from '@agentdeck/contracts/panel-agent';

/**
 * Русские тексты карточки и следа — запасные к кодам `panelTextParams`.
 *
 * Сервер второй язык не держит (решение владельца): окно переводит код своим
 * словарём, а русская строка остаётся для старых записей следа и клиента без
 * словаря. `Record` по кодам контракта — пропуск кода краснеет на сборке, а
 * лишние/забытые подстановки — в `texts.test.ts`.
 */
/** Формы русского множественного числа: Intl.PluralRules('ru') знает one/few/many/other. */
export type RuPluralText = Record<
  Extract<PanelPluralForm, 'one' | 'few' | 'many' | 'other'>,
  string
>;

/** Текст кода: строка, а у кодов с подстановкой count — ещё и формы числа. */
export type PanelTextsRu = {
  [C in PanelTextCode]: C extends PanelTextCountCode ? string | RuPluralText : string;
};

export const PANEL_TEXTS_RU: PanelTextsRu = {
  'journal-where-am-i': 'Где человек в панели',
  'journal-list-sections': 'Список разделов панели',
  'journal-open-page': 'Открыта страница у человека',
  'journal-list-projects': 'Список проектов',
  'journal-create-project': 'Добавление проекта в реестр',
  'journal-list-chats': 'Список чатов',
  'journal-list-active-runs': 'Идущие прогоны чата',
  'journal-start-chat': 'Запуск агента в новом чате',
  'journal-list-test-groups': 'Группы тестов проекта',
  'journal-list-cases': 'Кейсы проекта',
  'journal-coverage': 'Покрытие требований',
  'journal-last-run': 'Последний прогон тестов',
  'journal-draft-cases': 'Запись кейсов из черновика',
  'journal-run-tests': 'Запуск агента тестов',
  'journal-list-contours': 'Список контуров',
  'journal-contour-status': 'Состояние контура',
  'journal-probe-contour': 'Проба контура',
  'journal-save-contour-draft': 'Черновик контура',
  'journal-enable-contour': 'Включение контура',
  'journal-list-rules': 'Список правил',
  'journal-list-skills': 'Список скиллов',
  'journal-list-hooks': 'Список хуков',
  'journal-list-mcp': 'Список MCP-серверов',
  'journal-list-permissions': 'Список прав',
  'journal-save-rule': 'Правка правила CLAUDE.md',
  'journal-toggle-rule': 'Включение или выключение правила',
  'journal-delete-rule': 'Удаление правила',
  'journal-save-skill': 'Правка скилла',
  'journal-delete-skill': 'Удаление скилла',
  'journal-add-permission': 'Добавление права',
  'journal-remove-permission': 'Удаление права',
  'journal-save-mcp': 'Правка MCP-сервера',
  'journal-delete-mcp': 'Удаление MCP-сервера',
  'journal-invalid-input': 'Вход не прошёл проверку схемы',
  'fact-diff': 'с диффом файла',
  'fact-truncated': 'карточка неполная',
  'fact-stale': 'не выполнено: цель изменилась после показа карточки',
  'summary-create-project': 'Добавить проект «{{title}}» в реестр панели',
  'summary-start-chat': 'Запустить агента: новый чат в проекте «{{project}}»',
  'summary-draft-cases': {
    one: 'Записать {{count}} кейс из черновика в библиотеку тестов',
    few: 'Записать {{count}} кейса из черновика в библиотеку тестов',
    many: 'Записать {{count}} кейсов из черновика в библиотеку тестов',
    other: 'Записать {{count}} кейса из черновика в библиотеку тестов',
  },
  'summary-run-tests-generate': 'Запустить агента тестов: написать кейсы в черновик',
  'summary-run-tests-run': {
    one: 'Запустить агента тестов: {{count}} кейс',
    few: 'Запустить агента тестов: {{count}} кейса',
    many: 'Запустить агента тестов: {{count}} кейсов',
    other: 'Запустить агента тестов: {{count}} кейса',
  },
  'summary-contour-draft-save': 'Сохранить черновик контура «{{title}}»',
  'summary-contour-draft-update': 'Обновить черновик контура «{{title}}»',
  'summary-enable-contour': 'Включить контур «{{title}}»: работа панели и CLI пойдёт через него',
  'summary-rule-add': 'Добавить правило «{{title}}» в CLAUDE.md',
  'summary-rule-edit': 'Изменить правило «{{title}}» в CLAUDE.md',
  'summary-rule-enable': 'Включить правило «{{title}}»',
  'summary-rule-disable': 'Выключить правило «{{title}}»',
  'summary-rule-delete': 'Удалить правило «{{title}}»',
  'summary-skill-create': 'Создать скилл «{{name}}»',
  'summary-skill-edit': 'Изменить скилл «{{name}}»',
  'summary-skill-delete': 'Удалить скилл «{{name}}»',
  'summary-permission-add': 'Добавить право {{decision}}: {{pattern}}',
  'summary-permission-remove': 'Удалить право {{rule}}',
  'summary-mcp-add': 'Добавить MCP-сервер «{{name}}»',
  'summary-mcp-edit': 'Изменить MCP-сервер «{{name}}»',
  'summary-mcp-delete': 'Удалить MCP-сервер «{{name}}»',
  'label-directory': 'Каталог',
  'label-title': 'Название',
  'label-project': 'Проект',
  'label-provider': 'Провайдер',
  'label-model': 'Модель',
  'label-contour': 'Контур',
  'label-file-edits': 'Правки файлов',
  'label-first-message': 'Первое сообщение',
  'label-case-add': 'Добавить · {{target}}',
  'label-case-update': 'Изменить · {{target}}',
  'label-draft': 'Черновик',
  'label-hidden': 'Не показано',
  'label-mode': 'Режим',
  'label-selected-cases': 'Кейсов в отборе',
  'label-group': 'Группа',
  'label-environment': 'Окружение',
  'label-scope': 'Пожелание',
  'label-warning': 'Внимание',
  'label-id': 'Идентификатор',
  'label-address': 'Адрес',
  'label-driver': 'Тип шлюза',
  'label-consumers': 'Где работает',
  'label-key': 'Ключ',
  'label-enabling': 'Включение',
  'label-active-now': 'Сейчас активен',
  'label-last-probe': 'Последняя проба',
  'label-what-happens': 'Что произойдёт',
  'label-file': 'Файл',
  'label-new-file': 'Новый файл',
  'label-file-shape': 'Форма файла',
  'label-besides-file': 'Кроме файла',
  'label-rule-title': 'Заголовок',
  'label-skill-name': 'Имя',
  'label-transport': 'Транспорт',
  'label-command': 'Команда',
  'label-secrets-by-you': 'Секреты введёте вы',
  'value-model-default': 'по умолчанию CLI',
  'value-edits-allowed': 'разрешены',
  'value-edits-denied': 'нет — только чтение',
  'value-cases-hidden': {
    one: 'ещё {{count}} кейс не поместился в карточку — одобрить нельзя, выберите часть через caseIds',
    few: 'ещё {{count}} кейса не поместились в карточку — одобрить нельзя, выберите часть через caseIds',
    many: 'ещё {{count}} кейсов не поместились в карточку — одобрить нельзя, выберите часть через caseIds',
    other:
      'ещё {{count}} кейса не поместились в карточку — одобрить нельзя, выберите часть через caseIds',
  },
  'value-mode-generate': 'генерация кейсов в черновик',
  'value-mode-run': 'прогон кейсов',
  'value-group-all': 'вся библиотека',
  'value-provider-other':
    '{{provider}} (активный CLI — {{active}}, но агент тестов запускает {{provider}})',
  'value-contour-refuses': 'откажет: {{reason}}',
  'value-run-already': 'уже идёт прогон {{id}}',
  'value-consumers-default': 'по умолчанию (ассистент панели)',
  'value-key-kept': 'ключ сохранён, не меняется',
  'value-key-by-you': 'вводите вы: после сохранения откроется поле ключа',
  'value-enabling-separate': 'не включается — отдельным действием',
  'value-active-none': 'нет (провайдер по умолчанию)',
  'value-key-accepted': 'сохранён, принят пробой',
  'value-key-state': 'сохранён ({{state}})',
  'value-probe-never': 'не проверялся',
  'value-happens-rollback': 'применения «{{previous}}» снимаются, затем проба и пробный запрос',
  'value-happens-probe': 'проба и пробный запрос через шлюз панели',
  'value-file-shape':
    '{{path}} перепишется целиком в формате панели (отступ 2 пробела): часть строк диффа меняет только отступы, не значения',
  'note-rule-group-off':
    'Правило остаётся выключенным: его гасит группа, одиночный переключатель её не пересилит.',
  'note-skill-folder-delete': 'Папка {{dir}} удаляется целиком (копия — в истории).',
  'note-skill-folder-files': 'Вместе с ней файлы: {{files}}',
  'note-permission-mark-only':
    'Право выключено и в файле отсутствует: снимается только отметка панели.',
  'note-mcp-oauth-delete': 'Сохранённый вход OAuth этого сервера тоже удаляется.',
  'note-mcp-rename': 'Переименование: отметки и вход OAuth переезжают с «{{from}}» на «{{to}}».',
  'note-hook-group-off': 'Хук остаётся выключенным: его гасит группа.',
  'note-hook-local-file': 'Хук из settings.local.json панель не переключает: файл не изменится.',
  'note-copy-in-history': 'Копия файла остаётся в истории.',
  'note-entity-group-off': 'Остаётся выключенным: его гасит группа.',
  'note-folder-move': 'Папка {{from}} переносится в {{to}}.',
  'journal-list-groups': 'Список групп',
  'journal-save-group': 'Сохранение группы',
  'summary-group-create': 'Создать группу «{{name}}» (включится сразу)',
  'summary-group-edit': 'Изменить группу «{{name}}»',
  'label-members': 'Участники',
  'journal-toggle-group': 'Переключение группы',
  'summary-group-enable': 'Включить группу «{{name}}» вместе с участниками',
  'summary-group-disable': 'Выключить группу «{{name}}» вместе с участниками',
  'label-env-keys': 'Переменные',
  'journal-delete-group': 'Удаление группы',
  'summary-group-delete': 'Удалить группу «{{name}}»',
  'journal-get-settings': 'Настройки панели',
  'journal-update-settings': 'Изменение настроек панели',
  'summary-settings-update': 'Изменить настройки панели: {{keys}}',
  'journal-switch-provider': 'Смена провайдера CLI',
  'summary-provider-switch': 'Переключить панель с {{from}} на {{to}}',
  'journal-list-endpoints': 'Список своих эндпоинтов',
  'journal-save-endpoint': 'Сохранение эндпоинта',
  'summary-endpoint-create': 'Добавить эндпоинт «{{name}}»',
  'summary-endpoint-edit': 'Изменить эндпоинт «{{name}}»',
  'journal-probe-endpoint': 'Проверка связи с эндпоинтом',
  'journal-apply-endpoint': 'Применение эндпоинта к CLI',
  'summary-endpoint-apply': 'Записать эндпоинт «{{name}}» в конфигурацию {{provider}}',
  'journal-delete-endpoint': 'Удаление эндпоинта',
  'summary-endpoint-delete': 'Удалить эндпоинт «{{name}}»',
  'journal-get-dlp': 'Защита данных',
  'journal-save-dlp-rules': 'Сохранение правил защиты данных',
  'summary-dlp-rules': {
    one: 'Сохранить {{count}} правило защиты данных вместо нынешнего списка',
    few: 'Сохранить {{count}} правила защиты данных вместо нынешнего списка',
    many: 'Сохранить {{count}} правил защиты данных вместо нынешнего списка',
    other: 'Сохранить {{count}} правила защиты данных вместо нынешнего списка',
  },
  'journal-toggle-dlp-proxy': 'Запуск или остановка прокси защиты',
  'summary-dlp-start': 'Запустить прокси защиты данных',
  'summary-dlp-stop': 'Остановить прокси защиты данных',
  'journal-list-integrations': 'Список интеграций',
  'journal-save-integration': 'Сохранение интеграции',
  'summary-integration-save': 'Изменить настройки интеграции {{id}}',
  'journal-check-integration': 'Проверка интеграции',
  'journal-forget-integration': 'Отключение интеграции',
  'summary-integration-forget': 'Забыть интеграцию {{id}}: стереть токен и выключить',
  'journal-save-hook': 'Сохранение хука',
  'summary-hook-add': 'Добавить хук на событие {{event}}',
  'summary-hook-edit': 'Изменить хук на событие {{event}}',
  'label-matchers': 'Условие (matcher)',
  'journal-toggle-hook': 'Переключение хука',
  'summary-hook-enable': 'Включить хук на событие {{event}}',
  'summary-hook-disable': 'Выключить хук на событие {{event}}',
  'journal-delete-hook': 'Удаление хука',
  'summary-hook-delete': 'Удалить хук на событие {{event}}',
  'journal-list-env': 'Переменные окружения',
  'journal-set-env': 'Запись переменной окружения',
  'summary-env-set': 'Записать переменную {{key}} ({{source}})',
  'journal-delete-env': 'Удаление переменной окружения',
  'summary-env-delete': 'Удалить переменную {{key}} ({{source}})',
  'journal-read-claude-md': 'Чтение глобальных инструкций',
  'journal-save-claude-md': 'Перезапись глобальных инструкций',
  'summary-claude-md-save': 'Переписать глобальный CLAUDE.md',
  'journal-list-scripts': 'Список скриптов',
  'journal-read-script': 'Чтение скрипта',
  'journal-save-script': 'Сохранение скрипта',
  'summary-script-create': 'Создать скрипт {{id}}',
  'summary-script-edit': 'Изменить скрипт {{id}}',
  'journal-delete-script': 'Удаление скрипта',
  'summary-script-delete': 'Удалить скрипт {{id}}',
  'journal-list-commands': 'Список команд',
  'journal-toggle-skill': 'Переключение скилла',
  'journal-toggle-mcp': 'Переключение MCP-сервера',
  'journal-toggle-permission': 'Переключение правила прав',
  'summary-entity-enable': 'Включить «{{name}}»',
  'summary-entity-disable': 'Выключить «{{name}}»',
  'journal-search-help': 'Поиск по справке',
  'journal-read-help-topic': 'Чтение темы справки',
  'journal-list-help-topics': 'Список тем справки',
  'journal-overview': 'Обзор конфигурации',
  'journal-search-panel': 'Поиск по конфигурации',
  'journal-analytics-summary': 'Сводка аналитики',
  'journal-compare-providers': 'Сравнение CLI',
  'journal-env-passport': 'Паспорт среды',
  'journal-list-plugins': 'Список плагинов',
  'journal-list-available-plugins': 'Каталог плагинов',
  'journal-install-plugin': 'Установка плагина',
  'summary-plugin-install': 'Установить плагин {{id}}',
  'journal-uninstall-plugin': 'Удаление плагина',
  'summary-plugin-uninstall': 'Удалить плагин {{id}}',
  'journal-toggle-plugin': 'Переключение плагина',
  'summary-plugin-enable': 'Включить плагин {{id}}',
  'summary-plugin-disable': 'Выключить плагин {{id}}',
  'journal-update-plugin': 'Обновление плагина',
  'summary-plugin-update': 'Обновить плагин {{id}}',
  'label-version': 'Версия',
  'journal-add-marketplace': 'Подключение маркетплейса',
  'summary-marketplace-add': 'Подключить маркетплейс {{source}}',
  'journal-remove-marketplace': 'Отключение маркетплейса',
  'summary-marketplace-remove': 'Отключить маркетплейс {{name}}',
  'journal-list-history': 'Лента изменений',
  'journal-history-diff': 'Дифф правки из истории',
  'journal-revert-hunk': 'Откат блока правки',
  'summary-revert-hunk': 'Вернуть блок {{hunk}} в {{file}} к состоянию из копии',
  'label-backup': 'Копия',
  'journal-list-backups': 'Резервные копии',
  'journal-restore-backup': 'Восстановление из копии',
  'summary-restore-backup': 'Восстановить {{target}} из резервной копии целиком',
  'label-created': 'Создана',
  'journal-delete-project': 'Снятие проекта с учёта',
  'summary-delete-project': 'Убрать проект «{{name}}» из реестра панели (файлы остаются)',
  'journal-project-git-status': 'Состояние git проекта',
  'journal-list-worktrees': 'Рабочие копии проекта',
  'journal-list-test-runs': 'История прогонов тестов',
  'journal-read-test-run': 'Прогон тестов',
  'journal-lint-tests': 'Замечания библиотеки тестов',
  'journal-stop-tests': 'Остановка прогона тестов',
  'summary-stop-tests': 'Остановить идущий прогон тестов ({{mode}})',
  'journal-delete-test-case': 'Удаление тест-кейса',
  'summary-delete-test-case': 'Удалить кейс «{{title}}»',
};

const ruPlural = new Intl.PluralRules('ru');

/** Шаблон кода с учётом числа: «1 кейс», «3 кейса», «5 кейсов» — вместо «кейс(ов)». */
export function panelTemplateRu(code: PanelTextCode, params?: PanelTextParams): string {
  const text: string | RuPluralText = PANEL_TEXTS_RU[code];
  if (typeof text === 'string') return text;
  const count = Number(params?.count);
  return text[Number.isFinite(count) ? (ruPlural.select(count) as keyof RuPluralText) : 'other'];
}

export function panelTextRu(code: PanelTextCode, params?: PanelTextParams): string {
  return formatPanelText(panelTemplateRu(code, params), params);
}

/** Сводка карточки: русский запасной текст и код с подстановками. */
export function summaryText(code: PanelTextCode, params: PanelTextParams = {}) {
  return { summary: panelTextRu(code, params), summaryCode: code, summaryParams: params };
}

/** Поле с данными: подпись кодом, значение как есть (путь, адрес, промпт). */
export function dataField(
  labelCode: PanelTextCode,
  value: string,
  labelParams?: PanelTextParams,
): PanelActionPreviewField {
  return {
    label: panelTextRu(labelCode, labelParams),
    labelCode,
    ...(labelParams ? { labelParams } : {}),
    value,
  };
}

/** Поле, значение которого пишет сама панель: и подпись, и значение кодом. */
export function textField(
  labelCode: PanelTextCode,
  valueCode: PanelTextCode,
  valueParams?: PanelTextParams,
): PanelActionPreviewField {
  return {
    label: panelTextRu(labelCode),
    labelCode,
    value: panelTextRu(valueCode, valueParams),
    valueCode,
    ...(valueParams ? { valueParams } : {}),
  };
}
