import type { GateScriptConfig } from './script.types.ts';

/**
 * Скрипт гейта для английского интерфейса панели.
 *
 * Отдельный шаблон, а не словарь внутри русского, намеренно: русский скрипт
 * обязан собираться байт в байт как раньше — иначе каждый уже установленный
 * гейт панель приняла бы за правку руками и перестала бы обновлять. Код обоих
 * шаблонов один и тот же; тест сравнивает их без комментариев и строк, так что
 * расхождение логики между языками краснеет сразу.
 */
export function buildEnglishGateScript(config: GateScriptConfig, core: string): string {
  return `// Prompt gate — generated by AgentDeck.
// Event: UserPromptSubmit. Looks at the text the PERSON TYPED, before it is sent.
//
// What it cannot see by design: files the agent read on its own, command
// output, tool contents, attachments. All of that reaches the model past the hook.
// There is no masking here: by the documentation, UserPromptSubmit cannot
// replace the prompt — only stop the send (exit code 2) or add a message.
//
// You may edit this file by hand: the panel notices the difference and will not
// overwrite it without an explicit reinstall. Rules come from the file below — edit them in the panel.

import { appendFileSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { stdin } from 'node:process';

const CONFIG = ${JSON.stringify(config, null, 2)};

${core}

/** Whether to keep the journal: the proxy flag in state.json, read now rather than at install. */
function journalEnabled() {
  if (!CONFIG.journalPath) return false;
  if (!CONFIG.statePath) return true;
  try {
    return JSON.parse(readFileSync(CONFIG.statePath, 'utf8')).settings?.dlp?.journal !== false;
  } catch {
    return true;
  }
}

/** The journal is shared with the proxy. It holds no values — only the rule and a count. */
function journal(entry) {
  if (!journalEnabled()) return;
  try {
    appendFileSync(CONFIG.journalPath, JSON.stringify(entry) + '\\n', 'utf8');
    if (statSync(CONFIG.journalPath).size > 2000000) {
      const lines = readFileSync(CONFIG.journalPath, 'utf8').split('\\n').filter(Boolean).slice(-500);
      writeFileSync(CONFIG.journalPath, lines.join('\\n') + '\\n', 'utf8');
    }
  } catch {
    // The journal is auxiliary: its failure must not stop the prompt from being sent.
  }
}

/** Warn without getting in the way. Empty stdout means the prompt goes as is. */
function warn(message) {
  process.stdout.write(JSON.stringify({ systemMessage: message }));
  process.exit(0);
}

let raw = '';
for await (const chunk of stdin) raw += chunk;

let payload = {};
try {
  payload = JSON.parse(raw || '{}');
} catch {
  // Could not parse — below this becomes "input shape not recognised".
}

// The documented field is user_prompt; prompt is accepted as a fallback.
let prompt;
if (typeof payload.user_prompt === 'string') prompt = payload.user_prompt;
else if (typeof payload.prompt === 'string') prompt = payload.prompt;

if (prompt === undefined) {
  // Input shape not recognised. Staying silent is wrong (nothing was checked), but
  // blocking every prompt over a format change would stop the person's work entirely.
  journal({
    at: new Date().toISOString(),
    path: 'hook:UserPromptSubmit',
    apiKind: 'prompt',
    decision: 'passed',
    bytes: raw.length,
    hits: [],
    reason: 'hook input shape not recognised — nothing was checked',
  });
  warn('AgentDeck: the gate could not parse the hook input, the prompt was NOT checked.');
}

let rules = [];
try {
  const parsed = JSON.parse(readFileSync(CONFIG.rulesPath, 'utf8'));
  rules = Array.isArray(parsed.rules) ? parsed.rules : [];
} catch {
  // No rules or a broken file: say so honestly and let the prompt through. Silence
  // is more dangerous here — the person would believe the check is working.
  warn('AgentDeck: the gate rules could not be read, the prompt was NOT checked.');
}

const matches = scanPrompt(prompt, rules);
if (matches.length === 0) process.exit(0);

const hits = summarize(matches);
const names = [...new Set(hits.map((hit) => hit.ruleName))].join(', ');
// A "block" rule stops the prompt whatever the general setting: it means
// "this must not leave at all".
const blocked = CONFIG.action === 'block' || hits.some((hit) => hit.action === 'block');

journal({
  at: new Date().toISOString(),
  path: 'hook:UserPromptSubmit',
  apiKind: 'prompt',
  decision: blocked ? 'blocked' : 'passed',
  bytes: prompt.length,
  hits,
  reason: names,
});

if (blocked) {
  // Exit code 2 is the only documented way to stop the send.
  // The text carries only rule NAMES: matched values can never get in here.
  process.stderr.write(
    'AgentDeck: prompt not sent — data protection rules matched: ' + names +
      '. Remove this data from the text or send it another way.',
  );
  process.exit(2);
}

warn('AgentDeck: the prompt contains data covered by the rules (' + names + '). Sent as is.');
`;
}
