import { describe, expect, it, beforeEach, afterEach } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { DlpRule } from '@agentdeck/contracts';
import { AppStore } from '../lib/app-store.ts';
import { applyPromptGate, describePromptGate, gateScriptPath } from './prompt-gate.ts';
import { buildGateScript, coreSource } from './prompt-gate/script.ts';
import { saveRules } from './dlp/rules-store.ts';

/**
 * Гейт говорит с человеком в CLI, а не в панели: его сообщения и шапка (она же
 * описание хука на странице «Хуки») обязаны быть на языке интерфейса. Проверяется
 * запуском настоящего скрипта и настоящим применением на временном диске.
 */

const CYRILLIC = /[А-Яа-яЁё]/;

const STAFF: DlpRule = {
  id: 'r1',
  name: 'Staff',
  enabled: true,
  kind: 'terms',
  terms: ['John Smith'],
  pattern: '',
  action: 'mask',
  label: 'NAME',
};

/** Код шаблона без комментариев, строк и ядра — то, что обязано совпасть у языков. */
function codeOnly(script: string): string {
  return script
    .replace(coreSource(), '')
    .replace(/^\s*\/\/.*$/gm, '')
    .replace(/\/\*\*[\s\S]*?\*\//g, '')
    .replace(/'(?:[^'\\\n]|\\.)*'/g, "''")
    .replace(/\s+/g, ' ');
}

describe('гейт на промпте: язык скрипта', () => {
  let dir: string;
  let hooksDir: string;
  let appDataDir: string;
  let store: AppStore;
  const location = () => ({ hooksDir, settingsPath: join(dir, 'settings.json'), appDataDir });

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'gate-lang-'));
    hooksDir = join(dir, 'hooks');
    appDataDir = join(dir, 'agentdeck');
    mkdirSync(hooksDir, { recursive: true });
    mkdirSync(appDataDir, { recursive: true });
    writeFileSync(join(dir, 'settings.json'), '{}', 'utf8');
    store = new AppStore(join(dir, 'state.json'));
    saveRules(appDataDir, [STAFF]);
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  const runEnglish = (payload: unknown, action: 'block' | 'warn') => {
    const script = join(dir, 'gate-en.mjs');
    writeFileSync(
      script,
      buildGateScript({
        rulesPath: join(appDataDir, 'dlp-rules.json'),
        journalPath: join(appDataDir, 'dlp-journal.jsonl'),
        action,
        language: 'en',
      }),
      'utf8',
    );
    return spawnSync(process.execPath, [script], {
      input: JSON.stringify(payload),
      encoding: 'utf8',
    });
  };

  it('английский скрипт отказывает, предупреждает и сообщает о сбое по-английски', () => {
    const blocked = runEnglish({ user_prompt: 'ask John Smith' }, 'block');
    expect(blocked.status).toBe(2);
    expect(blocked.stderr).toContain('prompt not sent');
    expect(blocked.stderr).toContain('Staff');
    expect(blocked.stderr).not.toMatch(CYRILLIC);

    const warned = runEnglish({ user_prompt: 'ask John Smith' }, 'warn');
    expect(warned.status).toBe(0);
    expect(JSON.parse(warned.stdout).systemMessage).toContain('Sent as is');
    expect(warned.stdout).not.toMatch(CYRILLIC);

    const unparsed = runEnglish({ unexpected: 'shape' }, 'block');
    expect(unparsed.status).toBe(0);
    expect(JSON.parse(unparsed.stdout).systemMessage).toContain('NOT checked');
    expect(unparsed.stdout).not.toMatch(CYRILLIC);
    const journal = readFileSync(join(appDataDir, 'dlp-journal.jsonl'), 'utf8');
    expect(journal).toContain('nothing was checked');
    expect(journal).not.toMatch(CYRILLIC);
  });

  it('шаблоны двух языков — один и тот же код', () => {
    const config = { rulesPath: 'r', journalPath: 'j', statePath: 's', action: 'block' as const };
    const ru = buildGateScript(config);
    const en = buildGateScript({ ...config, language: 'en' });
    expect(codeOnly(en.replace(/,\n\s*"language": "en"/, ''))).toBe(codeOnly(ru));
    // Шаблон без ядра не несёт ни одной русской буквы.
    expect(en.replace(coreSource(), '')).not.toMatch(CYRILLIC);
  });

  it('при английском интерфейсе ставится английский скрипт, и он не устаревший', () => {
    store.updateSettings({ language: 'en' });
    const info = applyPromptGate(store, location(), { enabled: true, action: 'block' });
    const text = readFileSync(gateScriptPath(hooksDir), 'utf8');

    expect(text.startsWith('// Prompt gate — generated by AgentDeck.')).toBe(true);
    expect(info.outdated).toBe(false);
    expect(info.customized).toBe(false);
  });

  it('смена языка делает свой скрипт устаревшим, применение пересобирает его на новом', () => {
    applyPromptGate(store, location(), { enabled: true, action: 'block' });
    expect(describePromptGate(store, location()).outdated).toBe(false);

    store.updateSettings({ language: 'en' });
    const stale = describePromptGate(store, location());
    expect(stale.outdated).toBe(true);
    expect(stale.customized).toBe(false);

    const rebuilt = applyPromptGate(store, location(), { enabled: true, action: 'block' });
    expect(rebuilt.outdated).toBe(false);
    expect(readFileSync(gateScriptPath(hooksDir), 'utf8')).toContain('Prompt gate');
  });

  it('правленный руками английский скрипт остаётся правкой', () => {
    store.updateSettings({ language: 'en' });
    applyPromptGate(store, location(), { enabled: true, action: 'block' });
    const path = gateScriptPath(hooksDir);
    writeFileSync(path, readFileSync(path, 'utf8').replace('Sent as is.', 'Sent anyway.'), 'utf8');

    const info = applyPromptGate(store, location(), { enabled: true, action: 'warn' });
    expect(info.customized).toBe(true);
    expect(readFileSync(path, 'utf8')).toContain('Sent anyway.');
  });
});
