export {
  useProjectGit,
  useCheckoutBranch,
  useCreateBranch,
  useCommitAll,
  usePullChanges,
  usePushBranch,
  useProjectWorktrees,
  useAddWorktree,
  useRemoveWorktree,
  useMirrorWorktree,
  useMirrorSettings,
  useSaveMirrorSettings,
  useBootstrapWorktree,
  useWorktreeBootstrapLog,
  projectGitKey,
} from './api/ProjectGitApi';
export type {
  ProjectGitChange,
  ProjectGitFileStatus,
  ProjectGitInfo,
  ProjectGitResult,
  ProjectWorktree,
  ProjectWorktreesInfo,
  ProjectWorktreesResult,
  WorktreeCopyAccess,
  WorktreeCopyGap,
  WorktreeCopyState,
  WorktreeMirrorReport,
  WorktreeMirrorSettings,
  WorktreeMirrorSkipped,
  WorktreeBootstrapState,
  WorktreeBootstrapStatus,
} from '@agentdeck/contracts';
