/**
 * Коды текстов карточки и следа для действий агента над проектом: файл
 * инструкций, MCP и права проекта, выбор группы, git (ветка, коммит, pull),
 * рабочие копии и их настройки, dev-сервер, чтение кода. Отдельный модуль, а не
 * строки в `panelTextParams`: общий словарь правят несколько волн параллельно,
 * и сюда он вливается одним разворотом. Без импортов — модуль доезжает до
 * телефона вместе с `panel-agent.ts`.
 */
export const PROJECT_TEXT_PARAMS = {
  // Чтения: строка следа.
  'journal-project-claude-md-read': [],
  'journal-project-mcp-list': [],
  'journal-project-permissions-list': [],
  'journal-project-group-choice': [],
  'journal-project-copy-settings': [],
  'journal-project-runner': [],
  'journal-project-files': [],
  'journal-project-file-read': [],
  // Правки: название следа и сводка карточки.
  'journal-project-claude-md-save': [],
  'summary-project-claude-md-save': ['project'],
  'journal-project-mcp-save': [],
  'summary-project-mcp-add': ['name', 'project'],
  'summary-project-mcp-edit': ['name', 'project'],
  'journal-project-mcp-delete': [],
  'summary-project-mcp-delete': ['name', 'project'],
  'journal-project-mcp-toggle': [],
  'summary-project-mcp-enable': ['name', 'project'],
  'summary-project-mcp-disable': ['name', 'project'],
  'journal-project-permission-add': [],
  'summary-project-permission-add': ['pattern', 'project'],
  'journal-project-permission-edit': [],
  'summary-project-permission-edit': ['pattern', 'project'],
  'journal-project-permission-remove': [],
  'summary-project-permission-remove': ['rule', 'project'],
  'label-project-decision': [],
  'value-project-decision-allow': [],
  'value-project-decision-ask': [],
  'value-project-decision-deny': [],
  'journal-project-group-choice-set': [],
  'summary-project-group-choice': ['group', 'project'],
  'summary-project-group-choice-reset': ['project'],
  'journal-project-git-checkout': [],
  'summary-project-git-checkout': ['branch', 'project'],
  'journal-project-git-branch': [],
  'summary-project-git-branch': ['branch', 'project'],
  'journal-project-git-commit': [],
  'summary-project-git-commit': ['count', 'branch', 'project'],
  'journal-project-git-pull': [],
  'summary-project-git-pull': ['project'],
  'label-project-git-branch': [],
  'label-project-git-message': [],
  'label-project-git-files': [],
  'label-project-git-source': [],
  'value-project-git-push-human': [],
  'journal-project-worktree-add': [],
  'summary-project-worktree-add': ['branch', 'project'],
  'journal-project-worktree-remove': [],
  'summary-project-worktree-remove': ['path'],
  'journal-project-worktree-bootstrap': [],
  'summary-project-worktree-bootstrap': ['path'],
  'journal-project-worktree-mirror': [],
  'summary-project-worktree-mirror': ['path'],
  'label-project-worktree-path': [],
  'label-project-worktree-install': [],
  'value-project-worktree-install-none': [],
  'value-project-worktree-force': [],
  'journal-project-mirror-settings': [],
  'summary-project-mirror-settings': ['project'],
  'journal-project-split-settings': [],
  'summary-project-split-settings': ['project'],
  'journal-project-runner-settings': [],
  'summary-project-runner-settings': ['target'],
  'journal-project-runner-autostart': [],
  'summary-project-runner-autostart-on': ['target'],
  'summary-project-runner-autostart-off': ['target'],
  'value-project-runner-autostart': [],
  'journal-project-runner-start': [],
  'summary-project-runner-start': ['target'],
  'journal-project-runner-stop': [],
  'summary-project-runner-stop': ['target'],
  'journal-project-free-port': [],
  'summary-project-free-port': ['port'],
  'label-project-runner-port': [],
  'label-project-runner-script': [],
  'label-project-port-holders': [],
} as const satisfies Record<string, readonly string[]>;
