/**
 * Коды текстов карточки и следа для действий агента в блоке «Тестирование»:
 * планы, ручные прогоны, эталоны, автотесты папки e2e, отчёты, обвязка
 * библиотеки. Отдельный модуль, а не строки в `panelTextParams`: общий словарь
 * правят несколько волн параллельно, и сюда вливается одним разворотом.
 * Без импортов — модуль доезжает до телефона вместе с `panel-agent.ts`.
 */
export const TESTS_BLOCK_TEXT_PARAMS = {
  'journal-read-tests-report': [],
  'journal-save-test-plan': [],
  'summary-save-test-plan-create': ['title'],
  'summary-save-test-plan-update': ['title'],
  'journal-delete-test-plan': [],
  'summary-delete-test-plan': ['title'],
  'journal-build-test-plan': [],
  'summary-build-test-plan': ['title', 'count'],
  'label-plan-recipe': [],
  'value-plan-recipe-smoke': [],
  'value-plan-recipe-diff': [],
  'value-plan-recipe-release': [],
  'value-plan-recipe-flaky': [],
  'journal-start-manual-run': [],
  'summary-start-manual-run': ['count'],
  'journal-record-manual-result': [],
  'summary-record-manual-result': ['title', 'status'],
  'journal-finish-manual-run': [],
  'summary-finish-manual-run': ['done', 'total'],
  'journal-cancel-manual-run': [],
  'summary-cancel-manual-run': ['done', 'total'],
  'journal-attach-test-note': [],
  'summary-attach-test-note': ['name', 'title'],
  'journal-accept-baseline': [],
  'summary-accept-baseline': ['title'],
  'label-baseline-diff': [],
  'value-baseline-replace': [],
  'journal-sync-e2e': [],
  'summary-sync-e2e': ['dir'],
  'journal-run-e2e': [],
  'summary-run-e2e-all': [],
  'summary-run-e2e-some': ['count'],
  'value-e2e-run-happens': [],
  'journal-stop-e2e': [],
  'summary-stop-e2e': [],
  'journal-save-shared-step': [],
  'summary-save-shared-step-create': ['title'],
  'summary-save-shared-step-update': ['title'],
  'journal-delete-shared-step': [],
  'summary-delete-shared-step': ['title'],
  'journal-save-test-environment': [],
  'summary-save-test-environment-create': ['title'],
  'summary-save-test-environment-update': ['title'],
  'journal-delete-test-environment': [],
  'summary-delete-test-environment': ['title'],
  'label-used-by-plans': [],
  'value-environment-secrets-go': [],
  'journal-save-test-schema': [],
  'summary-save-test-schema': [],
  'journal-save-test-view': [],
  'summary-save-test-view-create': ['title'],
  'summary-save-test-view-update': ['title'],
  'journal-delete-test-view': [],
  'summary-delete-test-view': ['title'],
  'journal-install-test-convention': [],
  'summary-install-test-convention': [],
  'value-convention-install': [],
  'journal-bulk-edit-cases': [],
  'summary-bulk-edit-cases': ['count'],
  'label-bulk-action': [],
  'journal-bulk-delete-cases': [],
  'summary-bulk-delete-cases': ['count'],
  'journal-draft-auto-accept': [],
  'summary-draft-auto-accept-on': [],
  'summary-draft-auto-accept-off': [],
  'journal-rollback-draft': [],
  'summary-rollback-draft': ['count'],
} as const satisfies Record<string, readonly string[]>;
