/**
 * Коды текстов карточки и следа для действий агента над настройками, контуром,
 * интеграциями, переносом среды, аналитикой, копиями и каркасом плагина.
 *
 * Отдельным модулем, а не строками внутри `panelTextParams`: общий список
 * правят несколько наборов действий, и каждый вносит свой одной строкой-спредом.
 * Код → имена подстановок, как и в общем списке; модуль без импортов — его
 * читают сервер без сборки, Metro телефона и переходник.
 */
export const PANEL_MANAGE_TEXT_PARAMS = {
  // Настройки: правила групп разделения, наблюдатель, модели, форматы, CLI.
  'journal-read-split-defaults': [],
  'journal-save-split-defaults': [],
  'summary-save-split-defaults': [],
  'label-split-human-only': [],
  'value-split-human-only': [],
  // Сита перед MR: выученные по тредам MR и счёт блокеров (28.09).
  'journal-read-sieves': [],
  'journal-delete-learned-sieve': [],
  'summary-delete-learned-sieve': ['class'],
  'label-sieve-sources': [],
  'journal-watcher-status': [],
  'journal-set-watcher': [],
  'summary-watcher-on': [],
  'summary-watcher-off': [],
  'label-watcher-cost': [],
  'value-watcher-cost': [],
  'value-watcher-off': [],
  'journal-list-models': [],
  'journal-format-check': [],
  'journal-read-account': [],
  'journal-cli-version': [],
  'journal-update-cli': [],
  'summary-update-cli': [],
  'label-cli-path': [],
  'value-update-cli-effect': [],
  'value-version-unknown': [],
  // Защита данных: проба текста и журнал прокси.
  'journal-dlp-preview': [],
  'journal-dlp-journal': [],
  'journal-clear-dlp-journal': [],
  'summary-clear-dlp-journal': [],
  'label-entries': [],
  'value-clear-dlp-journal': [],
  // Контур: снять применение, выключить, удалить, шлюз, расход, MCP.
  'journal-disable-contour': [],
  'summary-disable-contour': ['title'],
  'label-applied-targets': [],
  'value-applied-none': [],
  'value-disable-contour-effect': [],
  'journal-deactivate-contour': [],
  'summary-deactivate-contour': ['title'],
  'value-deactivate-contour-effect': [],
  'journal-delete-contour': [],
  'summary-delete-contour': ['title'],
  'value-delete-contour-effect': [],
  'journal-gateway-status': [],
  'journal-start-gateway': [],
  'summary-start-gateway': [],
  'label-port': [],
  'value-start-gateway-effect': [],
  'journal-restart-gateway': [],
  'summary-restart-gateway': [],
  'value-restart-gateway-effect': [],
  'journal-contour-spend': [],
  'journal-clear-contour-exhausted': [],
  'summary-clear-contour-exhausted': ['title'],
  'label-exhausted-at': [],
  'value-clear-exhausted-effect': [],
  'journal-contour-mcp': [],
  'summary-contour-mcp-connect': [],
  'summary-contour-mcp-disconnect': [],
  'label-mcp-server': [],
  'value-mcp-bridge-no-key': [],
  'value-mcp-disconnect-effect': [],
  // Интеграции: чтение Jira и Confluence, привязки проекта, MCP Atlassian.
  'journal-jira-projects': [],
  'journal-jira-search': [],
  'journal-jira-issue': [],
  'journal-confluence-spaces': [],
  'journal-confluence-search': [],
  'journal-confluence-page': [],
  'journal-list-integration-links': [],
  'journal-save-integration-link': [],
  'summary-save-integration-link': ['project'],
  'label-link-scope': [],
  'value-link-project': [],
  'label-jira-issue': [],
  'label-confluence-page': [],
  'label-forge-repo': [],
  'label-note': [],
  'journal-remove-integration-link': [],
  'summary-remove-integration-link': ['project'],
  'journal-atlassian-mcp': [],
  'summary-atlassian-mcp-disconnect': [],
  // Перенос среды и архив.
  'journal-portability-plan': [],
  'journal-apply-portability': [],
  'summary-apply-portability': ['source', 'target'],
  'label-target-root': [],
  'value-portability-backup': [],
  'journal-revert-portability': [],
  'summary-revert-portability': ['source', 'target'],
  'label-changed-since': [],
  'value-changed-since-none': [],
  'journal-portability-transfer': [],
  'journal-portability-subscriptions': [],
  'journal-env-transfer-preview': [],
  'journal-env-transfer-export': [],
  'summary-env-transfer-export': [],
  'label-archive-content': [],
  'value-archive-no-secrets': [],
  // Аналитика, копии, каркас плагина.
  'journal-analytics-live': [],
  'journal-session-where': [],
  'journal-stop-session': [],
  'summary-stop-session': ['session'],
  'label-process': [],
  'journal-delete-backup': [],
  'summary-delete-backup': ['name'],
  'value-delete-backup-effect': [],
  'journal-scaffold-plugin': [],
  'summary-scaffold-plugin': ['name'],
  'label-components': [],
  'value-components-none': [],
} as const satisfies Record<string, readonly string[]>;
