import { StyleSheet } from 'react-native';
import { colors, space, radius, font } from '../../../shared/config/theme';

export const styles = StyleSheet.create({
  root: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
    padding: space.sm,
    gap: space.sm,
  },
  options: { gap: space.sm, paddingHorizontal: space.xs },
  wrap: { flexWrap: 'wrap' },
  bar: { alignItems: 'flex-end' },
  input: { flex: 1, minHeight: 52 },
  gear: {
    width: 32,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gearText: { color: colors.textDim, fontSize: 18 },
  round: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pressed: { opacity: 0.75 },
  send: { backgroundColor: colors.accent },
  sendOff: { opacity: 0.4 },
  sendText: { color: colors.text, fontSize: 26, fontWeight: '700', lineHeight: 30 },
  mic: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised },
  micOn: { borderColor: colors.accent, backgroundColor: colors.accentDim },
  micText: { fontSize: 22, lineHeight: 26 },
  stop: { backgroundColor: colors.danger },
  stopMark: { width: 16, height: 16, borderRadius: 3, backgroundColor: colors.text },
  toggle: {
    paddingHorizontal: space.sm,
    paddingVertical: space.xs + 2,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  toggleOn: { borderColor: colors.accent, backgroundColor: colors.accentDim },
  toggleText: { color: colors.textDim, fontSize: font.small },
  toggleTextOn: { color: colors.text },
  chip: {
    paddingHorizontal: space.sm,
    paddingVertical: space.xs,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    maxWidth: 160,
  },
  chipOn: { borderColor: colors.accent, backgroundColor: colors.accentDim },
  chipOff: { opacity: 0.5 },
  chipText: { color: colors.textFaint, fontSize: font.small },
  chipTextOn: { color: colors.text },
  refused: { color: colors.danger },
  warn: { color: colors.warning },
  listening: { color: colors.accent },
});
