/**
 * Встроенные команды Claude Code — те, что живут внутри CLI, а не файлами.
 *
 * Почему каталог ведёт панель, а не читает с диска: файла у таких команд нет, и
 * списка своих команд CLI наружу не отдаёт. Значит остаётся одно честное
 * решение — держать сверенный с официальным справочником список здесь и прямо
 * говорить в интерфейсе, что его ведёт панель.
 *
 * Сверено со справочником команд Claude Code 2026-08-01 (CLI 2.1.178): 103
 * команды. Следствие, о котором стоит помнить: команда, появившаяся в CLI
 * позже, здесь не появится сама — её нужно дописать. Команды пользователя
 * (скиллы, файлы команд, плагины) этой проблемы не имеют: они читаются с диска
 * и появляются у любого человека автоматически.
 *
 * `kind` различает три вещи, которые в палитре выглядят одинаково: `builtin` —
 * поведение зашито в CLI; `skill` — «bundled skill», то есть промпт, который
 * CLI приносит с собой (и Claude может позвать его сам); `workflow` — связка,
 * раскидывающая работу по субагентам.
 */

export interface BuiltinCommand {
  /** Имя без слэша. */
  name: string;
  /** Подсказка по аргументам из справочника. */
  args?: string;
  kind: 'builtin' | 'skill' | 'workflow';
  /** Другие имена той же команды. */
  aliases?: string[];
  /** Команды, которые справочник называет рядом с этой. */
  related?: string[];
  /** Команда убрана из CLI — показываем помеченной, чтобы не искать её впустую. */
  removed?: true;
  ru: string;
  en: string;
}

export const BUILTIN_COMMANDS: readonly BuiltinCommand[] = [
  {
    name: 'add-dir',
    args: '<path>',
    kind: 'builtin',
    related: ['cd'],
    ru: 'Добавить каталог в доступ текущей сессии — не переезжая в него.',
    en: 'Add a working directory for file access during the current session.',
  },
  {
    name: 'advisor',
    args: '[model|off]',
    kind: 'builtin',
    ru: 'Включить или выключить советчика — вторую модель, которую спрашивают в ключевые моменты задачи.',
    en: 'Enable or disable the advisor tool, which consults a second model at key moments.',
  },
  {
    name: 'agents',
    kind: 'builtin',
    ru: 'Напоминание о субагентах: как их создать и где лежат их файлы (`.claude/agents/`).',
    en: 'Prints a reminder about creating and managing subagents in `.claude/agents/`.',
  },
  {
    name: 'autofix-pr',
    args: '[prompt]',
    kind: 'builtin',
    ru: 'Поднять облачную сессию, которая следит за PR текущей ветки и чинит падения CI и замечания ревью.',
    en: 'Spawn a cloud session that watches the branch PR and pushes fixes for CI failures and review comments.',
  },
  {
    name: 'background',
    args: '[prompt]',
    kind: 'builtin',
    aliases: ['bg'],
    related: ['fork', 'exit'],
    ru: 'Отцепить сессию в фон и освободить терминал; работа продолжится без вас.',
    en: 'Detach the session to run as a background agent and free the terminal.',
  },
  {
    name: 'batch',
    args: '<instruction>',
    kind: 'skill',
    related: ['plan'],
    ru: 'Разложить крупное изменение на 5–30 независимых кусков и сделать каждый отдельным субагентом в своём worktree, с PR на каждый.',
    en: 'Decompose a large change into 5–30 units and run each in its own worktree subagent with a PR.',
  },
  {
    name: 'branch',
    args: '[name]',
    kind: 'builtin',
    related: ['fork', 'resume', 'subtask'],
    ru: 'Ответвить разговор с этого места: попробовать другой путь, не потеряв нынешний.',
    en: 'Branch the conversation at this point to try a different direction without losing the original.',
  },
  {
    name: 'btw',
    args: '[question]',
    kind: 'builtin',
    ru: 'Задать вопрос в сторону — он не попадёт в историю разговора.',
    en: 'Ask a quick side question without adding it to the conversation.',
  },
  {
    name: 'bug',
    args: '[report]',
    kind: 'builtin',
    aliases: ['share'],
    related: ['feedback'],
    ru: 'Сообщить об ошибке: вы выбираете, сколько истории приложить, и подтверждаете отправку.',
    en: 'Report a bug: you choose how much session history to include and confirm before sending.',
  },
  {
    name: 'cd',
    args: '<path>',
    kind: 'builtin',
    related: ['add-dir'],
    ru: 'Перенести сессию в другой рабочий каталог, сохранив кэш промпта.',
    en: 'Move the session to a new working directory, preserving the prompt cache.',
  },
  {
    name: 'chrome',
    kind: 'builtin',
    ru: 'Настройки Claude в Chrome.',
    en: 'Configure Claude in Chrome settings.',
  },
  {
    name: 'claude-api',
    args: '[migrate|managed-agents-onboard]',
    kind: 'skill',
    ru: 'Подтянуть справку по Claude API под язык проекта: инструменты, стриминг, батчи, типичные грабли.',
    en: 'Load Claude API reference material for the project language: tool use, streaming, batches, pitfalls.',
  },
  {
    name: 'clear',
    args: '[name]',
    kind: 'builtin',
    aliases: ['reset', 'new'],
    related: ['resume', 'compact'],
    ru: 'Начать новый разговор с чистым контекстом; прежний остаётся в `/resume`.',
    en: 'Start a new conversation with empty context; the previous one stays available in `/resume`.',
  },
  {
    name: 'code-review',
    args: '[level] [--fix] [--comment] [target]',
    kind: 'skill',
    related: ['diff', 'simplify', 'ultrareview'],
    ru: 'Ревью текущего диффа на ошибки и лишнее; `--fix` применяет находки, `--comment` пишет их в PR.',
    en: 'Review the current diff for bugs and cleanups; `--fix` applies findings, `--comment` posts them to the PR.',
  },
  {
    name: 'color',
    args: '[color|default]',
    kind: 'builtin',
    ru: 'Цвет строки ввода в этой сессии.',
    en: 'Set the prompt bar color for the current session.',
  },
  {
    name: 'compact',
    args: '[instructions]',
    kind: 'builtin',
    related: ['clear', 'context'],
    ru: 'Освободить контекст, сжав разговор в сводку; можно задать, на чём сфокусироваться.',
    en: 'Free up context by summarizing the conversation, optionally with focus instructions.',
  },
  {
    name: 'config',
    args: '[key=value ...]',
    kind: 'builtin',
    aliases: ['settings'],
    ru: 'Настройки: тема, модель, стиль вывода; можно задать значение прямо аргументом.',
    en: 'Open settings — theme, model, output style; a `key=value` pair sets one directly.',
  },
  {
    name: 'context',
    args: '[all]',
    kind: 'builtin',
    related: ['compact'],
    ru: 'Показать, чем занят контекст: сеткой, с подсказками, что раздувает окно.',
    en: 'Visualize current context usage as a grid, with hints about what is filling the window.',
  },
  {
    name: 'copy',
    args: '[N]',
    kind: 'builtin',
    ru: 'Скопировать последний ответ (или N-й с конца) в буфер обмена.',
    en: 'Copy the last assistant response — or the Nth-latest — to the clipboard.',
  },
  {
    name: 'cost',
    kind: 'builtin',
    aliases: ['usage', 'stats'],
    ru: 'То же, что `/usage`: расход, лимиты плана, статистика.',
    en: 'Alias for `/usage`: spend, plan limits and activity stats.',
  },
  {
    name: 'dataviz',
    args: '[request]',
    kind: 'skill',
    ru: 'Помощь по графикам и дашбордам: выбор формы, цвет по смыслу, проверка палитры на контраст и дальтонизм.',
    en: 'Design guidance for charts and dashboards: chart form, colour by role, contrast and colourblind checks.',
  },
  {
    name: 'debug',
    args: '[description]',
    kind: 'skill',
    ru: 'Включить отладочный лог сессии и разобрать по нему, что пошло не так.',
    en: 'Enable debug logging for the session and troubleshoot by reading the debug log.',
  },
  {
    name: 'deep-research',
    args: '<question>',
    kind: 'workflow',
    ru: 'Разослать веб-поиски по вопросу, сверить источники и собрать отчёт со ссылками.',
    en: 'Fan out web searches, cross-check sources and synthesize a cited report.',
  },
  {
    name: 'design-login',
    kind: 'builtin',
    related: ['design-sync'],
    ru: 'Выдать доступ к дизайн-системе для `/design-sync` через аккаунт claude.ai.',
    en: 'Authorize design-system access for `/design-sync` with your claude.ai account.',
  },
  {
    name: 'design-sync',
    args: '[hint]',
    kind: 'skill',
    related: ['design-login'],
    ru: 'Собрать React-дизайн-систему репозитория и отправить в Claude Design, чтобы макеты рисовались вашими компонентами.',
    en: 'Convert the repo React design system and upload it to Claude Design so designs use your real components.',
  },
  {
    name: 'desktop',
    kind: 'builtin',
    aliases: ['app'],
    ru: 'Продолжить сессию в настольном приложении Claude Code.',
    en: 'Continue the current session in the Claude Code desktop app.',
  },
  {
    name: 'diff',
    kind: 'builtin',
    related: ['code-review'],
    ru: 'Просмотр незакоммиченных изменений и диффов по ходам.',
    en: 'Open an interactive viewer of uncommitted changes and per-turn diffs.',
  },
  {
    name: 'doctor',
    kind: 'skill',
    aliases: ['checkup'],
    ru: 'Осмотр установки: битые пути, лишние копии, нечитаемые настройки, дорогие скиллы и MCP, медленные хуки — с предложением починить.',
    en: 'Run a setup checkup — install health, PATH, unparseable settings, unused skills and MCP, slow hooks — and offer fixes.',
  },
  {
    name: 'effort',
    args: '[level|auto]',
    kind: 'builtin',
    related: ['model'],
    ru: 'Глубина продумывания: low, medium, high, xhigh, max; `auto` возвращает значение модели.',
    en: 'Set the model effort level: low, medium, high, xhigh, max; `auto` resets to the model default.',
  },
  {
    name: 'exit',
    kind: 'builtin',
    aliases: ['quit'],
    related: ['background'],
    ru: 'Выйти. В фоновой сессии — отцепиться, работа продолжится.',
    en: 'Exit the CLI; in an attached background session this detaches and the session keeps running.',
  },
  {
    name: 'export',
    args: '[filename]',
    kind: 'builtin',
    ru: 'Выгрузить разговор текстом — в файл или в буфер обмена.',
    en: 'Export the current conversation as plain text to a file or the clipboard.',
  },
  {
    name: 'fast',
    args: '[on|off]',
    kind: 'builtin',
    ru: 'Быстрый режим: тот же Opus, но с ускоренным выводом.',
    en: 'Toggle fast mode on or off.',
  },
  {
    name: 'feedback',
    args: '[report]',
    kind: 'builtin',
    related: ['bug'],
    ru: 'Отправить отзыв о Claude Code — тот же диалог и то же согласие, что у `/bug`.',
    en: 'Send product feedback, with the same dialog and consent step as `/bug`.',
  },
  {
    name: 'fewer-permission-prompts',
    kind: 'skill',
    related: ['permissions'],
    ru: 'Пройтись по транскриптам и предложить список разрешений, чтобы панель прав спрашивала реже.',
    en: 'Scan transcripts for common read-only calls and propose an allowlist to reduce permission prompts.',
  },
  {
    name: 'focus',
    kind: 'builtin',
    related: ['tui'],
    ru: 'Сжатый вид: только ваш запрос, однострочная сводка вызовов и итоговый ответ.',
    en: 'Toggle the focus view: your prompt, a one-line tool summary and the final response.',
  },
  {
    name: 'fork',
    args: '[prompt]',
    kind: 'builtin',
    related: ['branch', 'subtask'],
    ru: 'Скопировать разговор в отдельную фоновую сессию и продолжать работать здесь.',
    en: 'Copy the conversation into a new background session and keep working here.',
  },
  {
    name: 'goal',
    args: '[condition|clear]',
    kind: 'builtin',
    ru: 'Задать цель: Claude работает ход за ходом, пока условие не выполнено.',
    en: 'Set a goal: Claude keeps working across turns until the condition is met.',
  },
  {
    name: 'heapdump',
    kind: 'builtin',
    ru: 'Снимок памяти для разбора утечек. Внутри вся переписка и доступы — файл никому не отдавайте.',
    en: 'Write a heap snapshot for diagnosing memory usage; it contains the full conversation and credentials.',
  },
  {
    name: 'help',
    kind: 'builtin',
    ru: 'Справка и список доступных команд.',
    en: 'Show help and available commands.',
  },
  {
    name: 'hooks',
    kind: 'builtin',
    ru: 'Посмотреть хуки, привязанные к событиям инструментов.',
    en: 'View hook configurations for tool events.',
  },
  {
    name: 'ide',
    kind: 'builtin',
    ru: 'Интеграции с IDE и их состояние.',
    en: 'Manage IDE integrations and show status.',
  },
  {
    name: 'init',
    kind: 'builtin',
    related: ['memory'],
    ru: 'Завести в проекте стартовый `CLAUDE.md`.',
    en: 'Initialize the project with a starter `CLAUDE.md` guide.',
  },
  {
    name: 'insights',
    kind: 'builtin',
    ru: 'Отчёт по вашим сессиям: над чем работали, как шло, где тормозило.',
    en: 'Generate a report analyzing your sessions: project areas, patterns and friction points.',
  },
  {
    name: 'install-github-app',
    kind: 'builtin',
    ru: 'Поставить GitHub-приложение Claude на репозиторий, при желании с GitHub Actions.',
    en: 'Install the Claude GitHub App for a repository, optionally with GitHub Actions workflows.',
  },
  {
    name: 'install-slack-app',
    kind: 'builtin',
    ru: 'Поставить приложение Claude в Slack.',
    en: 'Install the Claude Slack app.',
  },
  {
    name: 'keybindings',
    kind: 'builtin',
    related: ['terminal-setup'],
    ru: 'Открыть файл горячих клавиш.',
    en: 'Open your keyboard shortcuts file.',
  },
  {
    name: 'login',
    kind: 'builtin',
    related: ['logout'],
    ru: 'Войти в аккаунт Anthropic.',
    en: 'Sign in to your Anthropic account.',
  },
  {
    name: 'logout',
    kind: 'builtin',
    related: ['login'],
    ru: 'Выйти из аккаунта.',
    en: 'Sign out from your Anthropic account.',
  },
  {
    name: 'loop',
    args: '[interval] [prompt]',
    kind: 'skill',
    aliases: ['proactive'],
    ru: 'Повторять запрос, пока сессия открыта; без интервала Claude сам выбирает паузу.',
    en: 'Run a prompt repeatedly while the session stays open; without an interval Claude self-paces.',
  },
  {
    name: 'mcp',
    args: '[reconnect|enable|disable]',
    kind: 'builtin',
    ru: 'Подключения MCP-серверов и их авторизация.',
    en: 'Manage MCP server connections and OAuth authentication.',
  },
  {
    name: 'memory',
    kind: 'builtin',
    related: ['init'],
    ru: 'Править файлы памяти `CLAUDE.md` и автопамять.',
    en: 'Edit `CLAUDE.md` memory files and manage auto-memory.',
  },
  {
    name: 'mobile',
    kind: 'builtin',
    aliases: ['ios', 'android'],
    ru: 'QR-код для установки мобильного приложения Claude.',
    en: 'Show a QR code to download the Claude mobile app.',
  },
  {
    name: 'model',
    args: '[model]',
    kind: 'builtin',
    related: ['effort'],
    ru: 'Сменить модель и сохранить её как модель по умолчанию.',
    en: 'Switch the model and save it as the default for new sessions.',
  },
  {
    name: 'passes',
    kind: 'builtin',
    related: ['upgrade'],
    ru: 'Поделиться бесплатной неделей Claude Code — если аккаунт подходит.',
    en: 'Share a free week of Claude Code with friends, if your account is eligible.',
  },
  {
    name: 'permissions',
    kind: 'builtin',
    related: ['fewer-permission-prompts'],
    ru: 'Правила разрешений: что можно, что спрашивать, что запрещено.',
    en: 'Manage allow, ask and deny rules for tool permissions.',
  },
  {
    name: 'plan',
    args: '[description]',
    kind: 'builtin',
    related: ['batch', 'ultraplan'],
    ru: 'Перейти в режим плана прямо из строки ввода.',
    en: 'Enter plan mode directly from the prompt.',
  },
  {
    name: 'plugin',
    args: '[subcommand]',
    kind: 'builtin',
    related: ['reload-plugins'],
    ru: 'Управление плагинами Claude Code.',
    en: 'Manage Claude Code plugins.',
  },
  {
    name: 'powerup',
    kind: 'builtin',
    ru: 'Короткие интерактивные уроки по возможностям Claude Code.',
    en: 'Discover Claude Code features through quick interactive lessons.',
  },
  {
    name: 'pr-comments',
    args: '[PR]',
    kind: 'builtin',
    removed: true,
    ru: 'Убрана в версии 2.1.91.',
    en: 'Removed in v2.1.91.',
  },
  {
    name: 'privacy-settings',
    kind: 'builtin',
    ru: 'Посмотреть и изменить настройки приватности.',
    en: 'View and update your privacy settings.',
  },
  {
    name: 'radio',
    kind: 'builtin',
    ru: 'Открыть в браузере lo-fi радио Claude FM.',
    en: 'Open Claude FM lo-fi radio in your browser.',
  },
  {
    name: 'recap',
    kind: 'builtin',
    related: ['insights'],
    ru: 'Однострочная сводка текущей сессии по требованию.',
    en: 'Generate a one-line summary of the current session on demand.',
  },
  {
    name: 'release-notes',
    kind: 'builtin',
    ru: 'Список изменений по версиям.',
    en: 'View the changelog in an interactive version picker.',
  },
  {
    name: 'reload-plugins',
    args: '[--force]',
    kind: 'builtin',
    related: ['plugin'],
    ru: 'Перечитать активные плагины без перезапуска.',
    en: 'Reload active plugins to apply pending changes without restarting.',
  },
  {
    name: 'reload-skills',
    kind: 'builtin',
    related: ['skills'],
    ru: 'Перечитать каталоги скиллов и команд: добавленное на диске станет доступным без перезапуска.',
    en: 'Re-scan skill and command directories so on-disk changes become available without restarting.',
  },
  {
    name: 'remote-control',
    kind: 'builtin',
    aliases: ['rc'],
    related: ['teleport'],
    ru: 'Отдать эту сессию под управление с claude.ai — продолжить с другого устройства.',
    en: 'Make this session available for Remote Control from claude.ai.',
  },
  {
    name: 'remote-env',
    kind: 'builtin',
    ru: 'Окружение по умолчанию для облачных агентов.',
    en: 'Choose the default environment for cloud agents.',
  },
  {
    name: 'rename',
    args: '[name]',
    kind: 'builtin',
    ru: 'Переименовать сессию; имя видно в строке ввода.',
    en: 'Rename the current session and show the name on the prompt bar.',
  },
  {
    name: 'resume',
    args: '[session]',
    kind: 'builtin',
    related: ['clear', 'branch', 'fork'],
    ru: 'Вернуться к прошлому разговору — по имени, по id или из списка.',
    en: 'Resume a conversation by ID or name, or open the session picker.',
  },
  {
    name: 'review',
    args: '[PR]',
    kind: 'builtin',
    related: ['code-review'],
    ru: 'Быстрое ревью пул-реквеста в один проход, только чтение.',
    en: 'Run a fast single-pass, read-only review of a GitHub pull request.',
  },
  {
    name: 'rewind',
    kind: 'builtin',
    ru: 'Откатить код и/или разговор к контрольной точке — или свернуть кусок разговора в сводку.',
    en: 'Rewind code and conversation to a checkpoint, or summarize from a selected message.',
  },
  {
    name: 'run',
    kind: 'skill',
    related: ['verify', 'run-skill-generator'],
    ru: 'Запустить приложение проекта и посмотреть на изменение вживую, а не только на зелёные тесты.',
    en: 'Launch and drive the project app to see a change working, not only passing tests.',
  },
  {
    name: 'run-skill-generator',
    kind: 'skill',
    related: ['run', 'verify'],
    ru: 'Написать проектный скилл, который научит `/run` и `/verify` собирать и запускать именно это приложение.',
    en: 'Write a per-project skill teaching `/run` and `/verify` how to build and launch this app.',
  },
  {
    name: 'sandbox',
    kind: 'builtin',
    ru: 'Включить или выключить режим песочницы.',
    en: 'Toggle sandbox mode.',
  },
  {
    name: 'schedule',
    args: '[description]',
    kind: 'builtin',
    related: ['loop'],
    ru: 'Расписания: создать, изменить, посмотреть или запустить задачу, которая идёт в облаке Anthropic.',
    en: 'Create, update, list or run routines that execute on Anthropic-managed cloud infrastructure.',
  },
  {
    name: 'scroll-speed',
    kind: 'builtin',
    ru: 'Скорость прокрутки колесом мыши.',
    en: 'Adjust mouse wheel scroll speed interactively.',
  },
  {
    name: 'security-review',
    kind: 'builtin',
    related: ['code-review'],
    ru: 'Разобрать изменения ветки на уязвимости.',
    en: 'Analyze the changes on the current branch for security vulnerabilities.',
  },
  {
    name: 'setup-bedrock',
    kind: 'builtin',
    ru: 'Мастер настройки Amazon Bedrock: доступ, регион, модели.',
    en: 'Configure Amazon Bedrock authentication, region and model pins.',
  },
  {
    name: 'setup-vertex',
    kind: 'builtin',
    ru: 'Мастер настройки Google Cloud: доступ, проект, регион, модели.',
    en: "Configure Google Cloud's Agent Platform authentication, project, region and model pins.",
  },
  {
    name: 'simplify',
    args: '[target]',
    kind: 'builtin',
    related: ['code-review'],
    ru: 'Найти в изменённом коде, что можно упростить, и применить правки.',
    en: 'Review the changed code for cleanup opportunities and apply the fixes.',
  },
  {
    name: 'skills',
    kind: 'builtin',
    related: ['reload-skills'],
    ru: 'Список доступных скиллов.',
    en: 'List available skills.',
  },
  {
    name: 'stats',
    kind: 'builtin',
    aliases: ['usage', 'cost'],
    ru: 'То же, что `/usage`.',
    en: 'Alias for `/usage`.',
  },
  {
    name: 'status',
    kind: 'builtin',
    ru: 'Состояние: версия, модель, аккаунт, связь. Отвечает сразу, не прерывая ответ.',
    en: 'Show version, model, account and connectivity; runs immediately without interrupting the response.',
  },
  {
    name: 'statusline',
    kind: 'builtin',
    ru: 'Настроить строку состояния Claude Code.',
    en: "Configure Claude Code's status line.",
  },
  {
    name: 'stickers',
    kind: 'builtin',
    ru: 'Заказать наклейки Claude Code.',
    en: 'Order Claude Code stickers.',
  },
  {
    name: 'stop',
    kind: 'builtin',
    related: ['background', 'exit'],
    ru: 'Остановить текущую фоновую сессию.',
    en: 'Stop the current background session.',
  },
  {
    name: 'subtask',
    args: '<task>',
    kind: 'builtin',
    related: ['fork', 'branch'],
    ru: 'Отдать побочную задачу субагенту, который унаследует разговор и вернёт результат сюда.',
    en: 'Spawn a forked subagent that inherits the conversation and reports back here.',
  },
  {
    name: 'tasks',
    kind: 'builtin',
    related: ['background'],
    ru: 'Фоновая работа этой сессии, включая уже отработавших субагентов.',
    en: 'View and manage background work in the session, including finished subagents.',
  },
  {
    name: 'team-onboarding',
    kind: 'builtin',
    ru: 'Собрать по вашей истории работы руководство для команды.',
    en: 'Generate a team onboarding guide from your Claude Code usage history.',
  },
  {
    name: 'teleport',
    kind: 'builtin',
    aliases: ['tp'],
    related: ['remote-control'],
    ru: 'Забрать веб-сессию claude.ai в этот терминал вместе с веткой и разговором.',
    en: 'Pull a Claude Code on the web session into this terminal with its branch and conversation.',
  },
  {
    name: 'terminal-setup',
    kind: 'builtin',
    related: ['keybindings'],
    ru: 'Настроить сочетания терминала — Shift+Enter и прочие.',
    en: 'Configure terminal keybindings for Shift+Enter and other shortcuts.',
  },
  {
    name: 'theme',
    kind: 'builtin',
    ru: 'Сменить цветовую тему.',
    en: 'Change the color theme.',
  },
  {
    name: 'tui',
    args: '[default|fullscreen]',
    kind: 'builtin',
    related: ['focus'],
    ru: 'Выбрать отрисовщик интерфейса и перезапуститься в нём, не потеряв разговор.',
    en: 'Set the terminal UI renderer and relaunch into it with the conversation intact.',
  },
  {
    name: 'ultraplan',
    args: '<prompt>',
    kind: 'builtin',
    related: ['plan'],
    ru: 'Составить план в отдельной сессии, посмотреть его в браузере и выполнить удалённо или вернуть в терминал.',
    en: 'Draft a plan in an ultraplan session, review it in the browser, then execute remotely or bring it back.',
  },
  {
    name: 'ultrareview',
    args: '[PR or branch]',
    kind: 'builtin',
    related: ['code-review'],
    ru: 'Глубокое ревью многими агентами в облачной песочнице.',
    en: 'Run a deep, multi-agent code review in a cloud sandbox.',
  },
  {
    name: 'upgrade',
    kind: 'builtin',
    related: ['passes'],
    ru: 'Открыть страницу перехода на более высокий тариф.',
    en: 'Open the upgrade page to switch to a higher plan tier.',
  },
  {
    name: 'usage',
    kind: 'builtin',
    aliases: ['cost', 'stats'],
    ru: 'Расход сессии, лимиты плана и статистика. Отвечает сразу.',
    en: 'Show session cost, plan usage limits and activity stats; runs immediately.',
  },
  {
    name: 'usage-credits',
    kind: 'builtin',
    related: ['usage'],
    ru: 'Кредиты сверх лимита: настроить или запросить у администратора.',
    en: 'Configure usage credits, or request them from your admin, when you hit a limit.',
  },
  {
    name: 'verify',
    kind: 'skill',
    related: ['run', 'code-review'],
    ru: 'Убедиться, что изменение работает: собрать, запустить и посмотреть на результат, а не поверить рассуждению.',
    en: 'Confirm a change works by building, running and observing the app rather than relying on reasoning.',
  },
  {
    name: 'vim',
    kind: 'builtin',
    removed: true,
    ru: 'Убрана в версии 2.1.92.',
    en: 'Removed in v2.1.92.',
  },
  {
    name: 'voice',
    args: '[hold|tap|off]',
    kind: 'builtin',
    ru: 'Голосовой ввод: удержанием, нажатием или выключить.',
    en: 'Toggle voice dictation, or enable it in a specific mode.',
  },
  {
    name: 'web-setup',
    kind: 'builtin',
    related: ['schedule'],
    ru: 'Связать аккаунт GitHub с Claude Code в вебе через локальный `gh`.',
    en: 'Connect your GitHub account to Claude Code on the web using your local `gh` credentials.',
  },
  {
    name: 'workflows',
    kind: 'builtin',
    related: ['batch'],
    ru: 'Ход выполняющихся связок: смотреть, приостанавливать, продолжать, сохранять.',
    en: 'Open the workflow progress view to watch, pause, resume or save workflows.',
  },
];
